development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://134.226.115.45:8983/solr/hydra-development" %>
test: &test
  adapter: solr
  url: http://localhost:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>

